Add LEAD Center Blurb to Footer
pioneers/website2 pull request #4
Opened 2023-03-28 02:41 UTC by dwai213

Also fixed the map link, which was previously broken.
Removed a redundant Header

2023-03-28 02:42 UTC, dwai213 commented on pie-website/src/components/Footer.js
> -            <h3>Get in Touch</h3>
Decided to remove this header because I think it's obvious that the information below are methods to communicate with us

2023-03-28 02:42 UTC, dwai213 commented on pie-website/src/components/Footer.js
> +            </div>
Added this new div with the [LEAD center prescribed wording](https://lead.berkeley.edu/wp-content/uploads/2014/12/student-org-domain-guidelines.pdf)

```
RSOs must include the following language, in a visible and readable font, on every page of their site
(e.g. In the footer): We are a student group acting independently of the University of California. We
take full responsibility for our organization and this website.
```

2023-03-28 02:43 UTC, dwai213 commented on pie-website/src/components/Footer.js
> -              <a href="https://www.google.com/maps/d/u/0/edit?mid=1zVieVgGgfPfW8yv6wN9TDJZPzDOW3XL9&ll=37.87498246754354%2C-122.25991490933154&z=19">
Fixed the link to a more useful map: https://www.google.com/maps/d/u/0/viewer?mid=1Sd6QurpSJK3xXEvOiISkWlKXj98&ll=37.87452100000002%2C-122.2592068&z=18

2023-03-28 02:43 UTC, dwai213 commented on pie-website/src/components/Footer.js
> -              <a href="https://www.google.com/maps/d/u/0/edit?mid=1zVieVgGgfPfW8yv6wN9TDJZPzDOW3XL9&ll=37.87498246754354%2C-122.25991490933154&z=19">
Also did some condensing

2023-03-28 02:50 UTC, dwai213 commented
I did some hacking via the Inspector console and thinks I got the pieces in the right place, but I can use some help reducing the font size of the LEAD center blurb. It should be maybe 2/3 the size of our email/address imo.

2023-03-28 02:51 UTC, dwai213 commented on pie-website/src/components/Footer.js
> -            <h3>Get in Touch</h3>
Plus, it took up vertical real estate that i need to eat up with my new blurb

2023-04-04 01:58 UTC, quantumfusion reviewed
LGTM... @jonathanpatkins not sure if the paragraph tag is correct for formatting?

2023-04-11 02:21 UTC, dwai213 commented
Bump again for @jonathanpatkins, let me know if you need anything from me :)

2023-04-19 02:03 UTC, jonathanpatkins requested changes
Moved the LEAD text to the very bottom of the footer

2023-04-19 02:06 UTC, jonathanpatkins approved these changes

2023-04-19 02:07 UTC, merged